### ISSUE TITLE
will not build

### ISSUE THREAD

**Issue by Alties-GamingYT** [Dragon-Forge-NEXUS/production-website#1]
```
2023-11-12T00:15:01.640448Z	Cloning repository...
2023-11-12T00:15:03.752506Z	From https://github.com/Dragon-Forge-NEXUS/production-website
2023-11-12T00:15:03.75332Z	 * branch            a1959d8b1a99d91d31ca3889e8d06dfd5d7a9dd2 -> FETCH_HEAD
2023-11-12T00:15:03.753509Z	
2023-11-12T00:15:04.27153Z	HEAD is now at a1959d8 just work
2023-11-12T00:15:04.272294Z	
2023-11-12T00:15:04.392835Z	
2023-11-12T00:15:04.428576Z	Success: Finished cloning repository files
2023-11-12T00:15:05.392919Z	Restoring from dependencies cache
2023-11-12T00:15:05.416087Z	Restoring from build output cache
2023-11-12T00:15:05.751513Z	Detected the following tools from environment: npm@9.6.7, nodejs@18.17.1
2023-11-12T00:15:05.752439Z	Installing project dependencies: npm clean-install --progress=false
2023-11-12T00:15:16.609892Z	
2023-11-12T00:15:16.610528Z	added 548 packages, and audited 549 packages in 10s
2023-11-12T00:15:16.61074Z	
2023-11-12T00:15:16.610886Z	228 packages are looking for funding
2023-11-12T00:15:16.611016Z	  run `npm fund` for details
2023-11-12T00:15:16.612801Z	
2023-11-12T00:15:16.613061Z	found 0 vulnerabilities
2023-11-12T00:15:16.634519Z	Executing user command: npm run build
2023-11-12T00:15:17.518814Z	
2023-11-12T00:15:17.519168Z	> build
2023-11-12T00:15:17.519343Z	> astro build
2023-11-12T00:15:17.519475Z	
2023-11-12T00:15:20.39574Z	12:15:20 AM [content] The "blog" collection does not have an associated folder in your `content` directory. Make sure the folder exists, or check your content config for typos.
2023-11-12T00:15:20.396962Z	12:15:20 AM [content] Types generated 553ms
2023-11-12T00:15:20.398425Z	12:15:20 AM [build] output target: static
2023-11-12T00:15:20.398822Z	12:15:20 AM [build] Collecting build info...
2023-11-12T00:15:20.400483Z	12:15:20 AM [build] Completed in 668ms.
2023-11-12T00:15:20.402464Z	12:15:20 AM [build] Building static entrypoints...
2023-11-12T00:15:21.895907Z	
2023-11-12T00:15:21.89638Z	╭── 🌼[35m daisyUI 3.9.4 [0mhttps://daisyui.com
2023-11-12T00:15:22.025236Z	│
2023-11-12T00:15:22.025619Z	├── [2m2[0m themes are enabled. How to add more themes:
2023-11-12T00:15:22.025804Z	│   https://daisyui.com/docs/themes
2023-11-12T00:15:22.025994Z	│
2023-11-12T00:15:22.02617Z	╰── [32m💚 Support daisyUI project[0m: https://opencollective.com/daisyui
2023-11-12T00:15:22.02634Z	
2023-11-12T00:15:22.756387Z	[31mCould not resolve "../../layouts/Dragonforgemedia.astro" from "src/pages/DragonForgeMedia/Discord.astro"[39m
2023-11-12T00:15:22.757146Z	file: [36m/opt/buildhome/repo/src/pages/DragonForgeMedia/Discord.astro[39m
2023-11-12T00:15:23.182195Z	 error   Could not resolve "../../layouts/Dragonforgemedia.astro" from "src/pages/DragonForgeMedia/Discord.astro"
2023-11-12T00:15:23.182597Z	  File:
2023-11-12T00:15:23.182783Z	    /opt/buildhome/repo/src/pages/DragonForgeMedia/Discord.astro
2023-11-12T00:15:23.18293Z	  Stacktrace:
2023-11-12T00:15:23.183064Z	RollupError: Could not resolve "../../layouts/Dragonforgemedia.astro" from "src/pages/DragonForgeMedia/Discord.astro"
2023-11-12T00:15:23.183273Z	    at error (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
2023-11-12T00:15:23.183428Z	    at ModuleLoader.handleInvalidResolvedId (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:24736:24)
2023-11-12T00:15:23.183616Z	    at file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:24698:26
2023-11-12T00:15:23.183751Z	
2023-11-12T00:15:23.215118Z	Failed: Error while executing user command. Exited with error code: 1
2023-11-12T00:15:23.225668Z	Failed: build command exited with code: 1
2023-11-12T00:15:24.175906Z	Failed: error occurred while running build command
```

**Comment by Alties-GamingYT** [comment]
Fixed
